# Generated by Django 2.2 on 2019-04-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('birth_year', models.CharField(max_length=200)),
                ('marriage', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images')),
                ('community_status', models.CharField(max_length=200)),
                ('instructor_possibility', models.BooleanField()),
                ('farm_area', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=200)),
                ('past_harvests', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.District')),
                ('subcounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SubCounty')),
            ],
        ),
    ]
