# Generated by Django 2.2 on 2019-04-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190411_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='subcounty',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
